Nicru guzzle
hiqdev/hiapi-nicru pull request #3
Opened 2018-11-16 07:22 UTC by bladeroot

2018-11-16 10:23 UTC, SilverFire requested changes
Сильно не вчитывался, но после изменений мне нравится больше чем до :)

Много где не хватает type hinting для параметров и возвращаемых типов, кое-где форматирование гуляет.

2018-11-16 10:23 UTC, SilverFire commented on src/NicRuTool.php
> +    public function getModule($name)
Type hinting для параметров и возвращаемого типа

2018-11-16 10:23 UTC, SilverFire commented on src/NicRuTool.php
> +        if (!key_exists($name, $this->modules)) {
Лучше в таком случае применять `!isset($this->modules[$name])` – это дешевле чем `key_exists`

2018-11-16 10:23 UTC, SilverFire commented on src/NicRuTool.php
> +    public function createModule($class)
Type hinting

2018-11-16 10:23 UTC, SilverFire commented on src/NicRuTool.php
> +    public function setHttpClient($httpClient): self
Type hinting

2018-11-16 10:23 UTC, SilverFire commented on src/modules/AbstractModule.php
> +    public $tool;
PHPDoc с указанием типов

2018-11-16 10:23 UTC, SilverFire commented on src/modules/AbstractModule.php
> +    public $base;
PHPDoc с указанием типов

2018-11-16 10:23 UTC, SilverFire commented on src/HttpClient.php
> +    protected $client;
PHPDoc с указанием типов

2018-11-16 10:23 UTC, SilverFire commented on src/HttpClient.php
> +    public function __construct(Client $client)
Я бы скорее писал зависимость на интерфейс ClientInterface из PSR-18
https://www.php-fig.org/psr/psr-18/

2018-11-16 10:23 UTC, SilverFire commented on src/modules/OrderModule.php
> +            throw new \Exception('action failed');
Нужно использовать локальные классы исключений, чтобы можно было ловить что-то конкретное, а не `\Exception`

2018-11-20 16:05 UTC, hiqsol commented on src/HttpClient.php
> +    /* @var object [[Client]] */
это пишется `@var Client` и всё

2018-11-20 16:05 UTC, hiqsol commented on src/HttpClient.php
> +     * @throws \hiapi\nicru\exceptions\NicRuException
не соответствует тому что реально бросается
чем неправильно, лучше вообще не писать

2018-11-20 16:05 UTC, hiqsol commented on src/NicRuTool.php
> +        'hosts'     => HostModule::class,
а где `contact` ?

2018-11-20 16:05 UTC, hiqsol commented on src/modules/AbstractModule.php
> +    /* @var object [[NicRuTool]] */
`@var NicRuTool`

2018-11-20 16:05 UTC, hiqsol commented on src/modules/AbstractModule.php
> +     * @throws \hiapi\nicru\requests\InvalidCallException|\hiapi\nicru\exceptions\InvalidObjectException
нужно просто `@throws InvalidCallException|InvalidObjectException`
у тебя же есть `use` для этих классов

2018-11-20 17:01 UTC, merged